package com.servicemaster.entities;
// Generated May 4, 2017 11:08:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GrnLine generated by hbm2java
 */
public class GrnLine  implements java.io.Serializable {


     private int grnLineId;
     private Grn grn;
     private Item item;
     private Float unitPrice;
     private Float receivedQuantity;
     private Float totalPrice;
     private Float rejectedQuantity;
     private String rejectedReason;
     private Date createdDate;
     private Date createdTime;
     private Integer createdUser;
     private Date modifiedDate;
     private Date modifiedTime;
     private Integer modifiedUser;
     private String remark;

    public GrnLine() {
    }

	
    public GrnLine(int grnLineId, Grn grn, Item item) {
        this.grnLineId = grnLineId;
        this.grn = grn;
        this.item = item;
    }
    public GrnLine(int grnLineId, Grn grn, Item item, Float unitPrice, Float receivedQuantity, Float totalPrice, Float rejectedQuantity, String rejectedReason, Date createdDate, Date createdTime, Integer createdUser, Date modifiedDate, Date modifiedTime, Integer modifiedUser, String remark) {
       this.grnLineId = grnLineId;
       this.grn = grn;
       this.item = item;
       this.unitPrice = unitPrice;
       this.receivedQuantity = receivedQuantity;
       this.totalPrice = totalPrice;
       this.rejectedQuantity = rejectedQuantity;
       this.rejectedReason = rejectedReason;
       this.createdDate = createdDate;
       this.createdTime = createdTime;
       this.createdUser = createdUser;
       this.modifiedDate = modifiedDate;
       this.modifiedTime = modifiedTime;
       this.modifiedUser = modifiedUser;
       this.remark = remark;
    }
   
    public int getGrnLineId() {
        return this.grnLineId;
    }
    
    public void setGrnLineId(int grnLineId) {
        this.grnLineId = grnLineId;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Float getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Float unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Float getReceivedQuantity() {
        return this.receivedQuantity;
    }
    
    public void setReceivedQuantity(Float receivedQuantity) {
        this.receivedQuantity = receivedQuantity;
    }
    public Float getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Float getRejectedQuantity() {
        return this.rejectedQuantity;
    }
    
    public void setRejectedQuantity(Float rejectedQuantity) {
        this.rejectedQuantity = rejectedQuantity;
    }
    public String getRejectedReason() {
        return this.rejectedReason;
    }
    
    public void setRejectedReason(String rejectedReason) {
        this.rejectedReason = rejectedReason;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public Integer getCreatedUser() {
        return this.createdUser;
    }
    
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedTime() {
        return this.modifiedTime;
    }
    
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
    public Integer getModifiedUser() {
        return this.modifiedUser;
    }
    
    public void setModifiedUser(Integer modifiedUser) {
        this.modifiedUser = modifiedUser;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


