package com.servicemaster.entities;
// Generated May 7, 2017 7:35:27 PM by Hibernate Tools 4.3.1

/**
 * GrnLineId generated by hbm2java
 */
public class GrnLineId implements java.io.Serializable {

    private int grnLineId;
    private String itemSubCategoryCategoryCategoryCode;
    private String itemSubCategorySubCategoryCode;
    private String itemItemCode;

    public GrnLineId() {
    }

    public GrnLineId(int grnLineId, String itemSubCategoryCategoryCategoryCode, String itemSubCategorySubCategoryCode, String itemItemCode) {
        this.grnLineId = grnLineId;
        this.itemSubCategoryCategoryCategoryCode = itemSubCategoryCategoryCategoryCode;
        this.itemSubCategorySubCategoryCode = itemSubCategorySubCategoryCode;
        this.itemItemCode = itemItemCode;
    }

    public int getGrnLineId() {
        return this.grnLineId;
    }

    public void setGrnLineId(int grnLineId) {
        this.grnLineId = grnLineId;
    }

    public String getItemSubCategoryCategoryCategoryCode() {
        return this.itemSubCategoryCategoryCategoryCode;
    }

    public void setItemSubCategoryCategoryCategoryCode(String itemSubCategoryCategoryCategoryCode) {
        this.itemSubCategoryCategoryCategoryCode = itemSubCategoryCategoryCategoryCode;
    }

    public String getItemSubCategorySubCategoryCode() {
        return this.itemSubCategorySubCategoryCode;
    }

    public void setItemSubCategorySubCategoryCode(String itemSubCategorySubCategoryCode) {
        this.itemSubCategorySubCategoryCode = itemSubCategorySubCategoryCode;
    }

    public String getItemItemCode() {
        return this.itemItemCode;
    }

    public void setItemItemCode(String itemItemCode) {
        this.itemItemCode = itemItemCode;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof GrnLineId)) {
            return false;
        }
        GrnLineId castOther = (GrnLineId) other;

        return (this.getGrnLineId() == castOther.getGrnLineId())
                && ((this.getItemSubCategoryCategoryCategoryCode() == null ? castOther.getItemSubCategoryCategoryCategoryCode() == null : this.getItemSubCategoryCategoryCategoryCode().equals(castOther.getItemSubCategoryCategoryCategoryCode())) || (this.getItemSubCategoryCategoryCategoryCode() != null && castOther.getItemSubCategoryCategoryCategoryCode() != null && this.getItemSubCategoryCategoryCategoryCode().equals(castOther.getItemSubCategoryCategoryCategoryCode())))
                && ((this.getItemSubCategorySubCategoryCode() == null ? castOther.getItemSubCategorySubCategoryCode() == null : this.getItemSubCategorySubCategoryCode().equals(castOther.getItemSubCategorySubCategoryCode())) || (this.getItemSubCategorySubCategoryCode() != null && castOther.getItemSubCategorySubCategoryCode() != null && this.getItemSubCategorySubCategoryCode().equals(castOther.getItemSubCategorySubCategoryCode())))
                && ((this.getItemItemCode() == null ? castOther.getItemItemCode() == null : this.getItemItemCode().equals(castOther.getItemItemCode())) || (this.getItemItemCode() != null && castOther.getItemItemCode() != null && this.getItemItemCode().equals(castOther.getItemItemCode())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getGrnLineId();
        result = 37 * result + (getItemSubCategoryCategoryCategoryCode() == null ? 0 : this.getItemSubCategoryCategoryCategoryCode().hashCode());
        result = 37 * result + (getItemSubCategorySubCategoryCode() == null ? 0 : this.getItemSubCategorySubCategoryCode().hashCode());
        result = 37 * result + (getItemItemCode() == null ? 0 : this.getItemItemCode().hashCode());
        return result;
    }

}
