package com.servicemaster.entities;
// Generated Jun 3, 2017 10:01:09 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service  implements java.io.Serializable {


     private int serviceId;
     private ServiceBay serviceBay;
     private Vehicle vehicle;
     private String serviceCode;
     private Date createdDate;
     private Date createdTime;
     private Integer createdUser;
     private Date modifiedDate;
     private Date modifiedTime;
     private Integer modifiedUser;
     private String servicecol;
     private Set billings = new HashSet(0);
     private Set serviceItems = new HashSet(0);

    public Service() {
    }

	
    public Service(int serviceId, ServiceBay serviceBay, Vehicle vehicle, String serviceCode) {
        this.serviceId = serviceId;
        this.serviceBay = serviceBay;
        this.vehicle = vehicle;
        this.serviceCode = serviceCode;
    }
    public Service(int serviceId, ServiceBay serviceBay, Vehicle vehicle, String serviceCode, Date createdDate, Date createdTime, Integer createdUser, Date modifiedDate, Date modifiedTime, Integer modifiedUser, String servicecol, Set billings, Set serviceItems) {
       this.serviceId = serviceId;
       this.serviceBay = serviceBay;
       this.vehicle = vehicle;
       this.serviceCode = serviceCode;
       this.createdDate = createdDate;
       this.createdTime = createdTime;
       this.createdUser = createdUser;
       this.modifiedDate = modifiedDate;
       this.modifiedTime = modifiedTime;
       this.modifiedUser = modifiedUser;
       this.servicecol = servicecol;
       this.billings = billings;
       this.serviceItems = serviceItems;
    }
   
    public int getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(int serviceId) {
        this.serviceId = serviceId;
    }
    public ServiceBay getServiceBay() {
        return this.serviceBay;
    }
    
    public void setServiceBay(ServiceBay serviceBay) {
        this.serviceBay = serviceBay;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public String getServiceCode() {
        return this.serviceCode;
    }
    
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public Integer getCreatedUser() {
        return this.createdUser;
    }
    
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedTime() {
        return this.modifiedTime;
    }
    
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
    public Integer getModifiedUser() {
        return this.modifiedUser;
    }
    
    public void setModifiedUser(Integer modifiedUser) {
        this.modifiedUser = modifiedUser;
    }
    public String getServicecol() {
        return this.servicecol;
    }
    
    public void setServicecol(String servicecol) {
        this.servicecol = servicecol;
    }
    public Set getBillings() {
        return this.billings;
    }
    
    public void setBillings(Set billings) {
        this.billings = billings;
    }
    public Set getServiceItems() {
        return this.serviceItems;
    }
    
    public void setServiceItems(Set serviceItems) {
        this.serviceItems = serviceItems;
    }




}


