package com.servicemaster.entities;
// Generated May 7, 2017 7:35:27 PM by Hibernate Tools 4.3.1

/**
 * SubCategoryPrinters generated by hbm2java
 */
public class SubCategoryPrinters implements java.io.Serializable {

    private SubCategoryPrintersId id;
    private Printer printer;
    private SubCategory subCategory;

    public SubCategoryPrinters() {
    }

    public SubCategoryPrinters(SubCategoryPrintersId id, Printer printer, SubCategory subCategory) {
        this.id = id;
        this.printer = printer;
        this.subCategory = subCategory;
    }

    public SubCategoryPrintersId getId() {
        return this.id;
    }

    public void setId(SubCategoryPrintersId id) {
        this.id = id;
    }

    public Printer getPrinter() {
        return this.printer;
    }

    public void setPrinter(Printer printer) {
        this.printer = printer;
    }

    public SubCategory getSubCategory() {
        return this.subCategory;
    }

    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }

}
