package com.servicemaster.entities;
// Generated May 7, 2017 7:35:27 PM by Hibernate Tools 4.3.1

/**
 * SubCategoryId generated by hbm2java
 */
public class SubCategoryId implements java.io.Serializable {

    private String categoryCategoryCode;
    private String subCategoryCode;

    public SubCategoryId() {
    }

    public SubCategoryId(String categoryCategoryCode, String subCategoryCode) {
        this.categoryCategoryCode = categoryCategoryCode;
        this.subCategoryCode = subCategoryCode;
    }

    public String getCategoryCategoryCode() {
        return this.categoryCategoryCode;
    }

    public void setCategoryCategoryCode(String categoryCategoryCode) {
        this.categoryCategoryCode = categoryCategoryCode;
    }

    public String getSubCategoryCode() {
        return this.subCategoryCode;
    }

    public void setSubCategoryCode(String subCategoryCode) {
        this.subCategoryCode = subCategoryCode;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SubCategoryId)) {
            return false;
        }
        SubCategoryId castOther = (SubCategoryId) other;

        return ((this.getCategoryCategoryCode() == null ? castOther.getCategoryCategoryCode() == null : this.getCategoryCategoryCode().equals(castOther.getCategoryCategoryCode())) || (this.getCategoryCategoryCode() != null && castOther.getCategoryCategoryCode() != null && this.getCategoryCategoryCode().equals(castOther.getCategoryCategoryCode())))
                && ((this.getSubCategoryCode() == null ? castOther.getSubCategoryCode() == null : this.getSubCategoryCode().equals(castOther.getSubCategoryCode())) || (this.getSubCategoryCode() != null && castOther.getSubCategoryCode() != null && this.getSubCategoryCode().equals(castOther.getSubCategoryCode())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getCategoryCategoryCode() == null ? 0 : this.getCategoryCategoryCode().hashCode());
        result = 37 * result + (getSubCategoryCode() == null ? 0 : this.getSubCategoryCode().hashCode());
        return result;
    }

}
