/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.servicemaster.internalFrames;

import com.servicemaster.data.SystemData;
import com.servicemaster.dialogs.ConfirmationDialog;
import com.servicemaster.dialogs.InformationDialog;
import com.servicemaster.forms.MainFrame;
import com.servicemaster.functions.KeyCodeFunctions;
import com.servicemaster.guiFunctions.LableFunctions;
import com.servicemaster.models.Address;
import com.servicemaster.models.BusinessAddress;
import com.servicemaster.models.BusinessAddressId;
import com.servicemaster.models.BusinessPartner;
import com.servicemaster.models.BusinessTelephone;
import com.servicemaster.models.BusinessTelephoneId;
import com.servicemaster.models.TelephoneNumber;
import com.servicemaster.utils.HibernateUtil;
import com.servicemaster.views.AddressView;
import com.servicemaster.views.BusinessPatnerView;
import com.servicemaster.views.TelephoneNumeberView;
import java.util.Date;
import java.util.List;
import java.util.Set;
import org.hibernate.Hibernate;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author RuwanM
 */
public class BusinessPartnerFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form BussinesPatnerFrame
     */
    public BusinessPartnerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtBussinesPatnerCode = new javax.swing.JTextField();
        lblCodeSearch = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstNameSearch = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblLastNameSearch = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        calBirthDay = new com.toedter.calendar.JDateChooser();
        cbxCustomer = new javax.swing.JCheckBox();
        cbxSupplier = new javax.swing.JCheckBox();
        cbxEmployee = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtRemark = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddressLine1 = new javax.swing.JTextField();
        lblAddressSearch = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelephoneNumber = new javax.swing.JTextField();
        lblTelephoneNumberSearch = new javax.swing.JLabel();
        txtAddressLine2 = new javax.swing.JTextField();
        txtAddressLine3 = new javax.swing.JTextField();
        lblClose = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        lblReset = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxIsActive = new javax.swing.JCheckBox();
        lblNicSearch = new javax.swing.JLabel();

        jCheckBox3.setText("jCheckBox1");

        setTitle("Bussines Partner");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setText("Bus. patner code :");

        txtBussinesPatnerCode.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblCodeSearch.setBackground(new java.awt.Color(150, 255, 150));
        lblCodeSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodeSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        lblCodeSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblCodeSearch.setOpaque(true);
        lblCodeSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCodeSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCodeSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCodeSearchMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("First name :");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Last name :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("NIC :");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Birth day :");

        txtFirstName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblFirstNameSearch.setBackground(new java.awt.Color(150, 255, 150));
        lblFirstNameSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFirstNameSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        lblFirstNameSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblFirstNameSearch.setOpaque(true);
        lblFirstNameSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFirstNameSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFirstNameSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFirstNameSearchMouseExited(evt);
            }
        });

        txtLastName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblLastNameSearch.setBackground(new java.awt.Color(150, 255, 150));
        lblLastNameSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLastNameSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        lblLastNameSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblLastNameSearch.setOpaque(true);
        lblLastNameSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLastNameSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLastNameSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLastNameSearchMouseExited(evt);
            }
        });

        txtNic.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        calBirthDay.setDate(new Date());
        calBirthDay.setDateFormatString("yyyy-MM-dd");
        calBirthDay.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        cbxCustomer.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxCustomer.setText("Customer");

        cbxSupplier.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxSupplier.setText("Supplier");

        cbxEmployee.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbxEmployee.setText("Employee");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Remark :");

        txtRemark.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setText("Address :");

        txtAddressLine1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblAddressSearch.setBackground(new java.awt.Color(150, 255, 150));
        lblAddressSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddressSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        lblAddressSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblAddressSearch.setOpaque(true);
        lblAddressSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddressSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddressSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddressSearchMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setText("Tele. Number :");

        txtTelephoneNumber.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblTelephoneNumberSearch.setBackground(new java.awt.Color(150, 255, 150));
        lblTelephoneNumberSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelephoneNumberSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        lblTelephoneNumberSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblTelephoneNumberSearch.setOpaque(true);
        lblTelephoneNumberSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTelephoneNumberSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTelephoneNumberSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTelephoneNumberSearchMouseExited(evt);
            }
        });

        txtAddressLine2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        txtAddressLine3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblClose.setBackground(new java.awt.Color(150, 255, 150));
        lblClose.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("Close");
        lblClose.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblSave.setBackground(new java.awt.Color(150, 255, 150));
        lblSave.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setText("Save");
        lblSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblSave.setOpaque(true);
        lblSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveMouseExited(evt);
            }
        });

        lblReset.setBackground(new java.awt.Color(150, 255, 150));
        lblReset.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReset.setText("Reset");
        lblReset.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblReset.setOpaque(true);
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResetMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel9.setText("Is Active :");

        cbxIsActive.setSelected(true);

        lblNicSearch.setBackground(new java.awt.Color(150, 255, 150));
        lblNicSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNicSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        lblNicSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblNicSearch.setOpaque(true);
        lblNicSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNicSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNicSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNicSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTelephoneNumberSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddressLine3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAddressSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtAddressLine2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblReset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbxCustomer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxSupplier)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbxEmployee))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFirstNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBussinesPatnerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(calBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNic, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLastNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNicSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxIsActive)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAddressSearch, lblCodeSearch, lblFirstNameSearch, lblLastNameSearch, lblNicSearch, lblTelephoneNumberSearch});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {calBirthDay, txtRemark});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAddressLine1, txtBussinesPatnerCode, txtFirstName, txtLastName, txtNic, txtTelephoneNumber});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblClose, lblReset, lblSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodeSearch)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtBussinesPatnerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstNameSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastNameSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNicSearch))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCustomer)
                    .addComponent(cbxSupplier)
                    .addComponent(cbxEmployee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAddressSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelephoneNumberSearch)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxIsActive))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {calBirthDay, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, lblAddressSearch, lblCodeSearch, lblFirstNameSearch, lblLastNameSearch, lblNicSearch, lblTelephoneNumberSearch, txtAddressLine1, txtBussinesPatnerCode, txtFirstName, txtLastName, txtNic, txtRemark, txtTelephoneNumber});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblClose, lblReset, lblSave});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCodeSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCodeSearchMouseClicked
        String businessPatnerCode = txtBussinesPatnerCode.getText().trim();
        List businessPartners = getBusinessPatnerByCode(businessPatnerCode, true);

        if (!businessPartners.isEmpty()) {
            BusinessPatnerView businessPatnerView = new BusinessPatnerView(businessPartners, this);
            MainFrame.desktopPane.add(businessPatnerView);
            businessPatnerView.setVisible(true);
        }
    }//GEN-LAST:event_lblCodeSearchMouseClicked

    private void lblCodeSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCodeSearchMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblCodeSearchMouseEntered

    private void lblCodeSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCodeSearchMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblCodeSearchMouseExited

    private void lblFirstNameSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFirstNameSearchMouseClicked
        String firstName = txtFirstName.getText().trim();
        List businessPartners = getBusinessPatnerByFirstName(firstName, true);

        if (!businessPartners.isEmpty()) {
            BusinessPatnerView businessPatnerView = new BusinessPatnerView(businessPartners, this);
            MainFrame.desktopPane.add(businessPatnerView);
            businessPatnerView.setVisible(true);
        }
    }//GEN-LAST:event_lblFirstNameSearchMouseClicked

    private void lblFirstNameSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFirstNameSearchMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblFirstNameSearchMouseEntered

    private void lblFirstNameSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFirstNameSearchMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblFirstNameSearchMouseExited

    private void lblLastNameSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLastNameSearchMouseClicked
        String lastName = txtLastName.getText().trim();
        List businessPartners = getBusinessPatnerByLastName(lastName, true);

        if (!businessPartners.isEmpty()) {
            BusinessPatnerView businessPatnerView = new BusinessPatnerView(businessPartners, this);
            MainFrame.desktopPane.add(businessPatnerView);
            businessPatnerView.setVisible(true);
        }
    }//GEN-LAST:event_lblLastNameSearchMouseClicked

    private void lblLastNameSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLastNameSearchMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblLastNameSearchMouseEntered

    private void lblLastNameSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLastNameSearchMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblLastNameSearchMouseExited

    private void lblAddressSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddressSearchMouseClicked
        String addressLine1 = txtAddressLine1.getText().trim();
        if (addressLine1.isEmpty() || addressLine1.split("-").length == 2) {
            List addresses = getAddressByCode(addressLine1.split("-")[0].trim(), true);

            if (!addresses.isEmpty()) {
                AddressView addressView = new AddressView(addresses, this);
                MainFrame.desktopPane.add(addressView);
                addressView.setVisible(true);
            }
        } else {
            List addresses = getAddressByLine1(addressLine1, true);

            if (!addresses.isEmpty()) {
                AddressView addressView = new AddressView(addresses, this);
                MainFrame.desktopPane.add(addressView);
                addressView.setVisible(true);
            }
        }
    }//GEN-LAST:event_lblAddressSearchMouseClicked

    private void lblAddressSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddressSearchMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblAddressSearchMouseEntered

    private void lblAddressSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddressSearchMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblAddressSearchMouseExited

    private void lblTelephoneNumberSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTelephoneNumberSearchMouseClicked
        String telephoneNumber = txtTelephoneNumber.getText().trim();
        if (telephoneNumber.isEmpty() || telephoneNumber.split("-").length == 2) {
            List telephoneNumbers = getTelephoneByCode(telephoneNumber.split("-")[0].trim(), true);

            if (!telephoneNumbers.isEmpty()) {
                TelephoneNumeberView telephoneNumeberView = new TelephoneNumeberView(telephoneNumbers, this);
                MainFrame.desktopPane.add(telephoneNumeberView);
                telephoneNumeberView.setVisible(true);
            }
        } else {
            List telephoneNumbers = getTelephoneByNumber(telephoneNumber, true);

            if (!telephoneNumbers.isEmpty()) {
                TelephoneNumeberView telephoneNumeberView = new TelephoneNumeberView(telephoneNumbers, this);
                MainFrame.desktopPane.add(telephoneNumeberView);
                telephoneNumeberView.setVisible(true);
            }
        }
    }//GEN-LAST:event_lblTelephoneNumberSearchMouseClicked

    private void lblTelephoneNumberSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTelephoneNumberSearchMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblTelephoneNumberSearchMouseEntered

    private void lblTelephoneNumberSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTelephoneNumberSearchMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblTelephoneNumberSearchMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        ConfirmationDialog.showMessageBox("Are you sure?", "Sure");
        if (ConfirmationDialog.option == ConfirmationDialog.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseClicked
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();

        if (txtNic.getText().trim().isEmpty()) {
            InformationDialog.showMessageBox("Please enter valid NIC", "Invalid");
        } else {
            if (txtBussinesPatnerCode.getText().trim().isEmpty()) {
                List busisessPartners = getBusinessPatnerByNic(txtNic.getText().trim(), false);
                if (busisessPartners.isEmpty()) {
                    KeyCodeFunctions keyCodeFunctions = new KeyCodeFunctions();
                    this.saveOrUpdateBisnussPatner(keyCodeFunctions.getKey("BPT", "Business partner code"), false);
                } else {
                    InformationDialog.showMessageBox("Customer already exists", "Exist");
                }
            } else {
                List busisessPartners = getBusinessPatnerByCode(txtBussinesPatnerCode.getText().trim(), false);
                if (busisessPartners.isEmpty()) {
                    InformationDialog.showMessageBox("Invalid Business Patner code. Please try again", "Invalid");
                } else {
                    ConfirmationDialog.showMessageBox("Do you want to update?", "Update");
                    if (ConfirmationDialog.option == ConfirmationDialog.YES_OPTION) {
                        this.saveOrUpdateBisnussPatner(txtBussinesPatnerCode.getText().trim(), true);
                    }
                }
            }
        }

        session.getTransaction().commit();
        session.close();

        this.clearAll();
    }//GEN-LAST:event_lblSaveMouseClicked

    private void saveOrUpdateBisnussPatner(String strBusinessPatnerCode, boolean bUpdate) {
        Date date = new Date();

        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction transaction = session.beginTransaction();

        BusinessPartner businessPartner = new BusinessPartner();
        businessPartner.setBusinessPartnerCode(strBusinessPatnerCode);
        businessPartner.setFirstName(txtFirstName.getText().trim().toUpperCase());
        businessPartner.setLastName(txtLastName.getText().trim().toUpperCase());
        businessPartner.setNic(txtNic.getText().trim().toUpperCase());
        businessPartner.setBirthDay(calBirthDay.getDate());
        businessPartner.setIsCustomer(cbxCustomer.isSelected());
        businessPartner.setIsSupplier(cbxSupplier.isSelected());
        businessPartner.setIsEmployee(cbxEmployee.isSelected());
        businessPartner.setIsActive(cbxIsActive.isSelected() ? 1 : 0);
        businessPartner.setRemarks(txtRemark.getText().trim());
        if (bUpdate) {
            businessPartner.setModifiedDate(date);
            businessPartner.setModifiedTime(date);
            businessPartner.setModifiedUser(MainFrame.user.getUserId());
        } else {
            businessPartner.setCreatedDate(date);
            businessPartner.setCreatedTime(date);
            businessPartner.setCreatedUser(MainFrame.user.getUserId());
        }

        session.saveOrUpdate(businessPartner);

        Address address = new Address();
        address.setAddressCode(txtAddressLine1.getText().split("-")[0].trim());
        address.setAdressLine1(txtAddressLine1.getText().split("-")[1].trim().toUpperCase());
        address.setAdressLine2(txtAddressLine2.getText().trim().toUpperCase());
        address.setAdressLine3(txtAddressLine3.getText().trim().toUpperCase());
        if (bUpdate) {
            address.setModifiedDate(date);
            address.setModifiedTime(date);
            address.setModifiedUser(MainFrame.user.getUserId());
        } else {
            address.setCreatedDate(date);
            address.setCreatedTime(date);
            address.setCreatedUser(MainFrame.user.getUserId());
        }

        BusinessAddressId businessAddressId = new BusinessAddressId(txtAddressLine1.getText().split("-")[0].trim(), strBusinessPatnerCode);
        BusinessAddress businessAddress = new BusinessAddress(businessAddressId, address, businessPartner);

        session.saveOrUpdate(businessAddress);

        TelephoneNumber telephoneNumber = new TelephoneNumber();
        telephoneNumber.setTelephoneNumberCode(txtTelephoneNumber.getText().split("-")[0].trim());
        telephoneNumber.setTelephoneNumber(txtTelephoneNumber.getText().split("-")[1].trim());
        if (bUpdate) {
            telephoneNumber.setModifiedDate(date);
            telephoneNumber.setModifiedTime(date);
            telephoneNumber.setModifiedUser(MainFrame.user.getUserId());
        } else {
            telephoneNumber.setCreatedDate(date);
            telephoneNumber.setCreatedTime(date);
            telephoneNumber.setCreatedUser(MainFrame.user.getUserId());
        }

        BusinessTelephoneId businessTelephoneId = new BusinessTelephoneId(txtTelephoneNumber.getText().split("-")[0].trim(), strBusinessPatnerCode);
        BusinessTelephone businessTelephone = new BusinessTelephone(businessTelephoneId, businessPartner, telephoneNumber);

        session.saveOrUpdate(businessTelephone);

        transaction.commit();
        session.close();

        if (bUpdate) {
            InformationDialog.showMessageBox(SystemData.RECORD_UPDATED_MESSAGE, SystemData.RECORD_UPDATED_HEADING);
        } else {
            InformationDialog.showMessageBox(SystemData.NEW_RECORD_ADDED_MESSAGE, SystemData.NEW_RECORD_ADDED_HEADING);
        }
        this.clearAll();
    }

    private void lblSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblSaveMouseEntered

    private void lblSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblSaveMouseExited

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        this.clearAll();
    }//GEN-LAST:event_lblResetMouseClicked

    private void lblResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblResetMouseEntered

    private void lblResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblResetMouseExited

    private void lblNicSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNicSearchMouseClicked
        String nic = txtNic.getText().trim();
        List businessPartners = getBusinessPatnerByNic(nic, true);

        if (!businessPartners.isEmpty()) {
            BusinessPatnerView businessPatnerView = new BusinessPatnerView(businessPartners, this);
            MainFrame.desktopPane.add(businessPatnerView);
            businessPatnerView.setVisible(true);
        }
    }//GEN-LAST:event_lblNicSearchMouseClicked

    private void lblNicSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNicSearchMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblNicSearchMouseEntered

    private void lblNicSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNicSearchMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblNicSearchMouseExited

    public void setBusinessPatnerCode(String businessPartnerCode) {
        txtBussinesPatnerCode.setText(businessPartnerCode);
    }

    public void setFirstName(String firstName) {
        txtFirstName.setText(firstName);
    }

    public void setLastName(String lastName) {
        txtLastName.setText(lastName);
    }

    public void setNic(String nic) {
        txtNic.setText(nic);
    }

    public void setBirthDay(Date birthDay) {
        this.calBirthDay.setDate(birthDay);
    }

    public void setIsCustomer(boolean isCustomer) {
        cbxCustomer.setSelected(isCustomer);
    }

    public void setIsSupplier(boolean isSupplier) {
        cbxSupplier.setSelected(isSupplier);
    }

    public void setIsEmployee(boolean isEmployee) {
        cbxEmployee.setSelected(isEmployee);
    }

    public void setRemark(String remark) {
        txtRemark.setText(remark);
    }

    public void setIsActive(boolean isActive) {
        cbxIsActive.setSelected(isActive);
    }

    public void setAddressLine1(String addressLine1) {
        txtAddressLine1.setText(addressLine1);
    }

    public void setAddressLine2(String addressLine2) {
        txtAddressLine2.setText(addressLine2);
    }

    public void setAddressLine3(String addressLine3) {
        txtAddressLine3.setText(addressLine3);
    }

    public void setTelephoneNumber(String telephoneNumber) {
        txtTelephoneNumber.setText(telephoneNumber);
    }

    public void setBusinessPatnerCodeEditable(boolean editable) {
        txtBussinesPatnerCode.setEditable(editable);
    }

    public void setNicEditable(boolean editable) {
        txtNic.setEditable(editable);
    }

    public void setLblSaveText(String text) {
        this.lblSave.setText(text);
    }

    private List getBusinessPatnerByCode(String businessPatnerCode, boolean like) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query;
        if (like) {
            query = session.createQuery("from BusinessPartner b join fetch b.businessAddresses join fetch b.businessTelephones where b.businessPartnerCode like :code");
            query.setParameter("code", "%" + businessPatnerCode + "%");
        } else {
            query = session.createQuery("from BusinessPartner b join fetch b.businessAddresses join fetch b.businessTelephones where b.businessPartnerCode = :code");
            query.setParameter("code", businessPatnerCode);
        }
        List list = query.list();
        for (Object object : list) {
            if (object instanceof BusinessPartner) {
                BusinessPartner businessPartner = (BusinessPartner) object;
                Hibernate.initialize(businessPartner.getBusinessAddresses());
                Hibernate.initialize(businessPartner.getBusinessTelephones());

                Set addresses = businessPartner.getBusinessAddresses();
                for (Object tempAddresse : addresses) {
                    if (tempAddresse instanceof BusinessAddress) {
                        BusinessAddress businessAddress = (BusinessAddress) tempAddresse;
                        Hibernate.initialize(businessAddress.getAddress());
                    }
                }

                Set businessTelephone = businessPartner.getBusinessTelephones();
                for (Object tempTelephone : businessTelephone) {
                    if (tempTelephone instanceof BusinessTelephone) {
                        BusinessTelephone telephone = (BusinessTelephone) tempTelephone;
                        Hibernate.initialize(telephone.getTelephoneNumber());
                    }
                }
            }
        }
        session.getTransaction().commit();
        session.close();
        return list;
    }

    private List getBusinessPatnerByNic(String nic, boolean like) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query;
        if (like) {
            query = session.createQuery("from BusinessPartner b join fetch b.businessAddresses join fetch b.businessTelephones where b.nic like :nic");
            query.setParameter("nic", "%" + nic + "%");
        } else {
            query = session.createQuery("from BusinessPartner b join fetch b.businessAddresses join fetch b.businessTelephones where b.nic = :nic");
            query.setParameter("nic", nic);
        }
        List list = query.list();
        for (Object object : list) {
            if (object instanceof BusinessPartner) {
                BusinessPartner businessPartner = (BusinessPartner) object;
                Hibernate.initialize(businessPartner.getBusinessAddresses());
                Hibernate.initialize(businessPartner.getBusinessTelephones());

                Set addresses = businessPartner.getBusinessAddresses();
                for (Object tempAddresse : addresses) {
                    if (tempAddresse instanceof BusinessAddress) {
                        BusinessAddress businessAddress = (BusinessAddress) tempAddresse;
                        Hibernate.initialize(businessAddress.getAddress());
                    }
                }

                Set businessTelephone = businessPartner.getBusinessTelephones();
                for (Object tempTelephone : businessTelephone) {
                    if (tempTelephone instanceof BusinessTelephone) {
                        BusinessTelephone telephone = (BusinessTelephone) tempTelephone;
                        Hibernate.initialize(telephone.getTelephoneNumber());
                    }
                }
            }
        }
        session.getTransaction().commit();
        session.close();
        return list;
    }

    private List getBusinessPatnerByFirstName(String businessPatnerFirstName, boolean like) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query;
        if (like) {
            query = session.createQuery("from BusinessPartner b join fetch b.businessAddresses join fetch b.businessTelephones where b.firstName like :name");
            query.setParameter("name", "%" + businessPatnerFirstName + "%");
        } else {
            query = session.createQuery("from BusinessPartner b join fetch b.businessAddresses join fetch b.businessTelephones where b.firstName = :name");
            query.setParameter("name", businessPatnerFirstName);
        }
        List list = query.list();
        for (Object object : list) {
            if (object instanceof BusinessPartner) {
                BusinessPartner businessPartner = (BusinessPartner) object;
                Hibernate.initialize(businessPartner.getBusinessAddresses());
                Hibernate.initialize(businessPartner.getBusinessTelephones());

                Set addresses = businessPartner.getBusinessAddresses();
                for (Object tempAddresse : addresses) {
                    if (tempAddresse instanceof BusinessAddress) {
                        BusinessAddress businessAddress = (BusinessAddress) tempAddresse;
                        Hibernate.initialize(businessAddress.getAddress());
                    }
                }

                Set businessTelephone = businessPartner.getBusinessTelephones();
                for (Object tempTelephone : businessTelephone) {
                    if (tempTelephone instanceof BusinessTelephone) {
                        BusinessTelephone telephone = (BusinessTelephone) tempTelephone;
                        Hibernate.initialize(telephone.getTelephoneNumber());
                    }
                }
            }
        }
        session.getTransaction().commit();
        session.close();
        return list;
    }

    private List getBusinessPatnerByLastName(String businessPatnerLastName, boolean like) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query;
        if (like) {
            query = session.createQuery("from BusinessPartner b join fetch b.businessAddresses join fetch b.businessTelephones where b.lastName like :name");
            query.setParameter("name", "%" + businessPatnerLastName + "%");
        } else {
            query = session.createQuery("from BusinessPartner b join fetch b.businessAddresses join fetch b.businessTelephones where b.lastName = :name");
            query.setParameter("name", businessPatnerLastName);
        }
        List list = query.list();
        for (Object object : list) {
            if (object instanceof BusinessPartner) {
                BusinessPartner businessPartner = (BusinessPartner) object;
                Hibernate.initialize(businessPartner.getBusinessAddresses());
                Hibernate.initialize(businessPartner.getBusinessTelephones());

                Set addresses = businessPartner.getBusinessAddresses();
                for (Object tempAddresse : addresses) {
                    if (tempAddresse instanceof BusinessAddress) {
                        BusinessAddress businessAddress = (BusinessAddress) tempAddresse;
                        Hibernate.initialize(businessAddress.getAddress());
                    }
                }

                Set businessTelephone = businessPartner.getBusinessTelephones();
                for (Object tempTelephone : businessTelephone) {
                    if (tempTelephone instanceof BusinessTelephone) {
                        BusinessTelephone telephone = (BusinessTelephone) tempTelephone;
                        Hibernate.initialize(telephone.getTelephoneNumber());
                    }
                }
            }
        }
        session.getTransaction().commit();
        session.close();
        return list;
    }

    private List getAddressByCode(String addressCode, boolean like) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query;
        if (like) {
            query = session.createQuery("from Address a where a.addressCode like :code");
            query.setParameter("code", "%" + addressCode + "%");
        } else {
            query = session.createQuery("from Address a where a.addressCode = :code");
            query.setParameter("code", addressCode);
        }
        List list = query.list();
        session.getTransaction().commit();
        session.close();
        return list;
    }

    private List getAddressByLine1(String addressName, boolean like) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query;
        if (like) {
            query = session.createQuery("from Address a where a.adressLine1 like :name");
            query.setParameter("name", "%" + addressName + "%");
        } else {
            query = session.createQuery("from Address a where a.adressLine1 = :name");
            query.setParameter("name", addressName);
        }
        List list = query.list();
        session.getTransaction().commit();
        session.close();
        return list;
    }

    private List getTelephoneByCode(String telephoneCode, boolean like) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query;
        if (like) {
            query = session.createQuery("from TelephoneNumber t where t.telephoneNumberCode like :code");
            query.setParameter("code", "%" + telephoneCode + "%");
        } else {
            query = session.createQuery("from TelephoneNumber t where t.telephoneNumberCode = :code");
            query.setParameter("code", telephoneCode);
        }
        List list = query.list();
        session.getTransaction().commit();
        session.close();
        return list;
    }

    private List getTelephoneByNumber(String telephoneNumber, boolean like) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query query;
        if (like) {
            query = session.createQuery("from TelephoneNumber t where t.telephoneNumber like :name");
            query.setParameter("name", "%" + telephoneNumber + "%");
        } else {
            query = session.createQuery("from TelephoneNumber t where t.telephoneNumber = :name");
            query.setParameter("name", telephoneNumber);
        }
        List list = query.list();
        session.getTransaction().commit();
        session.close();
        return list;
    }

    public void clearAll() {
        txtBussinesPatnerCode.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtNic.setText("");
        calBirthDay.setDate(new Date());
        cbxCustomer.setSelected(false);
        cbxSupplier.setSelected(false);
        cbxEmployee.setSelected(false);
        txtRemark.setText("");
        txtAddressLine1.setText("");
        txtAddressLine2.setText("");
        txtAddressLine3.setText("");
        txtTelephoneNumber.setText("");
        cbxIsActive.setSelected(true);
        txtBussinesPatnerCode.setEditable(true);
        txtNic.setEditable(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calBirthDay;
    private javax.swing.JCheckBox cbxCustomer;
    private javax.swing.JCheckBox cbxEmployee;
    private javax.swing.JCheckBox cbxIsActive;
    private javax.swing.JCheckBox cbxSupplier;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAddressSearch;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCodeSearch;
    private javax.swing.JLabel lblFirstNameSearch;
    private javax.swing.JLabel lblLastNameSearch;
    private javax.swing.JLabel lblNicSearch;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblTelephoneNumberSearch;
    private javax.swing.JTextField txtAddressLine1;
    private javax.swing.JTextField txtAddressLine2;
    private javax.swing.JTextField txtAddressLine3;
    private javax.swing.JTextField txtBussinesPatnerCode;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtRemark;
    private javax.swing.JTextField txtTelephoneNumber;
    // End of variables declaration//GEN-END:variables
}
