/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.servicemaster.internalFrames;

import com.servicemaster.data.SystemData;
import com.servicemaster.dialogs.InformationDialog;
import com.servicemaster.functions.JdbcConnection;
import com.servicemaster.supportClasses.ButtonFunctions;
import java.sql.Connection;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.joda.time.DateTime;

/**
 *
 * @author Ruwan Madawala
 */
public class SalesReportFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form SalesReportFrame
     */
    public SalesReportFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionGroup = new javax.swing.ButtonGroup();
        reportGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        btnReset2 = new javax.swing.JButton();
        btnVeiw = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        optionPanel = new javax.swing.JPanel();
        dateChooserDaily = new com.toedter.calendar.JDateChooser();
        rbtMonthly = new javax.swing.JRadioButton();
        monthChooserMonthly = new com.toedter.calendar.JMonthChooser();
        rbtWeekly = new javax.swing.JRadioButton();
        dateChooserDateRangeEnd = new com.toedter.calendar.JDateChooser();
        rbtDaily = new javax.swing.JRadioButton();
        rbtDateRange = new javax.swing.JRadioButton();
        dateChooserDateRangeStart = new com.toedter.calendar.JDateChooser();
        reportPanel = new javax.swing.JPanel();
        rbtSalesReport = new javax.swing.JRadioButton();
        rbtOutstandingReport = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Sales Reports");

        btnReset2.setBackground(new java.awt.Color(150, 255, 150));
        btnReset2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnReset2.setText("Reset");
        btnReset2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnReset2.setContentAreaFilled(false);
        btnReset2.setOpaque(true);
        btnReset2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReset2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReset2MouseExited(evt);
            }
        });
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });

        btnVeiw.setBackground(new java.awt.Color(150, 255, 150));
        btnVeiw.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnVeiw.setText("View");
        btnVeiw.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnVeiw.setContentAreaFilled(false);
        btnVeiw.setOpaque(true);
        btnVeiw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVeiwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVeiwMouseExited(evt);
            }
        });
        btnVeiw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiwActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(150, 255, 150));
        btnClose.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(true);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        optionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Potions"));

        dateChooserDaily.setDate(new Date());
        dateChooserDaily.setDateFormatString("yyyy-MM-dd");

        optionGroup.add(rbtMonthly);
        rbtMonthly.setText("Monthly");
        rbtMonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMonthlyActionPerformed(evt);
            }
        });

        monthChooserMonthly.setEnabled(false);

        optionGroup.add(rbtWeekly);
        rbtWeekly.setText("Weekly");
        rbtWeekly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtWeeklyActionPerformed(evt);
            }
        });

        dateChooserDateRangeEnd.setDate(new Date());
        dateChooserDateRangeEnd.setDateFormatString("yyyy-MM-dd");
        dateChooserDateRangeEnd.setEnabled(false);

        optionGroup.add(rbtDaily);
        rbtDaily.setSelected(true);
        rbtDaily.setText("Daily");
        rbtDaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDailyActionPerformed(evt);
            }
        });

        optionGroup.add(rbtDateRange);
        rbtDateRange.setText("Date Range");
        rbtDateRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDateRangeActionPerformed(evt);
            }
        });

        dateChooserDateRangeStart.setDate(new Date());
        dateChooserDateRangeStart.setDateFormatString("yyyy-MM-dd");
        dateChooserDateRangeStart.setEnabled(false);

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtWeekly)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addComponent(rbtMonthly)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monthChooserMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addComponent(rbtDaily)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateChooserDaily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addComponent(rbtDateRange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateChooserDateRangeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(dateChooserDateRangeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        optionPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbtDaily, rbtDateRange, rbtMonthly, rbtWeekly});

        optionPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateChooserDaily, dateChooserDateRangeEnd, dateChooserDateRangeStart, monthChooserMonthly});

        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateChooserDaily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtDaily))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtWeekly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtMonthly)
                    .addComponent(monthChooserMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtDateRange)
                    .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dateChooserDateRangeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateChooserDateRangeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        optionPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateChooserDaily, dateChooserDateRangeEnd, dateChooserDateRangeStart, monthChooserMonthly, rbtDaily, rbtMonthly, rbtWeekly});

        reportPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Report"));

        reportGroup.add(rbtSalesReport);
        rbtSalesReport.setSelected(true);
        rbtSalesReport.setText("Sales Report");
        rbtSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSalesReportActionPerformed(evt);
            }
        });

        reportGroup.add(rbtOutstandingReport);
        rbtOutstandingReport.setText("Outstanding Report");
        rbtOutstandingReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOutstandingReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addComponent(rbtOutstandingReport)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addComponent(rbtSalesReport)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        reportPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbtOutstandingReport, rbtSalesReport});

        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtSalesReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtOutstandingReport)
                .addContainerGap())
        );

        reportPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbtOutstandingReport, rbtSalesReport});

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReset2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVeiw, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClose, btnReset2, btnVeiw});

        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVeiw, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClose, btnReset2, btnVeiw});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReset2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReset2MouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnReset2MouseEntered

    private void btnReset2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReset2MouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnReset2MouseExited

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        this.clearAll();
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnVeiwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeiwMouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnVeiwMouseEntered

    private void btnVeiwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeiwMouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnVeiwMouseExited

    private void btnVeiwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiwActionPerformed
        Date start_date = new Date();
        Date end_date = new Date();
        String reportName;

        if (rbtSalesReport.isSelected()) {
            reportName = "reports/SalesReport.jasper";
            if (rbtWeekly.isSelected()) {
                DateTime dateTime = new DateTime().minusDays(7);
                start_date = dateTime.toDate();
                end_date = new Date();

                System.out.println(start_date);
                System.out.println(end_date);
            } else if (rbtMonthly.isSelected()) {
                int month = monthChooserMonthly.getMonth();
                DateTime dateTime = new DateTime().withMonthOfYear(month + 1);

                start_date = dateTime.dayOfMonth().withMinimumValue().toDate();
                end_date = dateTime.dayOfMonth().withMaximumValue().toDate();

                System.out.println(start_date);
                System.out.println(end_date);
            } else if (rbtDateRange.isSelected()) {
                start_date = dateChooserDateRangeStart.getDate();
                end_date = dateChooserDateRangeEnd.getDate();

                System.out.println(start_date);
                System.out.println(end_date);
            } else {
                start_date = dateChooserDaily.getDate();
                end_date = dateChooserDaily.getDate();

                System.out.println(start_date);
                System.out.println(end_date);
            }
        } else if (rbtOutstandingReport.isSelected()) {
            reportName = "reports/OutsdandingReport.jasper";
        } else {
            reportName = "";
        }

        if (!reportName.isEmpty()) {
            try {
                JdbcConnection jbConnection = new JdbcConnection();
                Connection connection = jbConnection.getConnection();

                Map map = new HashMap();
                map.put("start_date", start_date);
                map.put("end_date", end_date);

                JasperPrint jasperPrint = JasperFillManager.fillReport(reportName, map, connection);
                if (jasperPrint.getPages().size() > 0) {
                    JasperViewer.viewReport(jasperPrint, false);
                } else {
                    InformationDialog.showMessageBox("No records found", "Not Found", this);
                }
            } catch (JRException ex) {
                Logger.getLogger(SalesReportFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnVeiwActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void rbtDailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDailyActionPerformed
        this.enableComponents();
    }//GEN-LAST:event_rbtDailyActionPerformed

    private void rbtWeeklyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtWeeklyActionPerformed
        this.enableComponents();
    }//GEN-LAST:event_rbtWeeklyActionPerformed

    private void rbtMonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMonthlyActionPerformed
        this.enableComponents();
    }//GEN-LAST:event_rbtMonthlyActionPerformed

    private void rbtDateRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDateRangeActionPerformed
        this.enableComponents();
    }//GEN-LAST:event_rbtDateRangeActionPerformed

    private void rbtOutstandingReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOutstandingReportActionPerformed
        this.enableComponents();
    }//GEN-LAST:event_rbtOutstandingReportActionPerformed

    private void rbtSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSalesReportActionPerformed
        this.enableComponents();
    }//GEN-LAST:event_rbtSalesReportActionPerformed

    private void enableComponents() {
        if (rbtOutstandingReport.isSelected()) {
            rbtDaily.setEnabled(false);
            rbtWeekly.setEnabled(false);
            rbtMonthly.setEnabled(false);
            rbtDateRange.setEnabled(false);
            dateChooserDaily.setEnabled(false);
            monthChooserMonthly.setEnabled(false);
            dateChooserDateRangeEnd.setEnabled(false);
            dateChooserDateRangeStart.setEnabled(false);
        } else if (rbtSalesReport.isSelected()) {
            if (rbtDaily.isSelected()) {
                dateChooserDaily.setEnabled(true);
                monthChooserMonthly.setEnabled(false);
                dateChooserDateRangeEnd.setEnabled(false);
                dateChooserDateRangeStart.setEnabled(false);
            } else if (rbtWeekly.isSelected()) {
                dateChooserDaily.setEnabled(false);
                monthChooserMonthly.setEnabled(false);
                dateChooserDateRangeEnd.setEnabled(false);
                dateChooserDateRangeStart.setEnabled(false);
            } else if (rbtMonthly.isSelected()) {
                dateChooserDaily.setEnabled(false);
                monthChooserMonthly.setEnabled(true);
                dateChooserDateRangeEnd.setEnabled(false);
                dateChooserDateRangeStart.setEnabled(false);
            } else if (rbtDateRange.isSelected()) {
                dateChooserDaily.setEnabled(false);
                monthChooserMonthly.setEnabled(false);
                dateChooserDateRangeEnd.setEnabled(true);
                dateChooserDateRangeStart.setEnabled(true);
            }

            rbtDaily.setEnabled(true);
            rbtWeekly.setEnabled(true);
            rbtMonthly.setEnabled(true);
            rbtDateRange.setEnabled(true);
        }
    }

    private void clearAll() {
        rbtDaily.setSelected(true);
        dateChooserDaily.setEnabled(true);
        monthChooserMonthly.setEnabled(false);
        dateChooserDateRangeEnd.setEnabled(false);
        dateChooserDateRangeStart.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnVeiw;
    private com.toedter.calendar.JDateChooser dateChooserDaily;
    private com.toedter.calendar.JDateChooser dateChooserDateRangeEnd;
    private com.toedter.calendar.JDateChooser dateChooserDateRangeStart;
    private javax.swing.JPanel mainPanel;
    private com.toedter.calendar.JMonthChooser monthChooserMonthly;
    private javax.swing.ButtonGroup optionGroup;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JRadioButton rbtDaily;
    private javax.swing.JRadioButton rbtDateRange;
    private javax.swing.JRadioButton rbtMonthly;
    private javax.swing.JRadioButton rbtOutstandingReport;
    private javax.swing.JRadioButton rbtSalesReport;
    private javax.swing.JRadioButton rbtWeekly;
    private javax.swing.ButtonGroup reportGroup;
    private javax.swing.JPanel reportPanel;
    // End of variables declaration//GEN-END:variables
}
