/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.servicemaster.internalFrames;

import com.servicemaster.data.SystemData;
import com.servicemaster.dialogs.ConfirmationDialog;
import com.servicemaster.dialogs.InformationDialog;
import com.servicemaster.forms.MainFrame;
import com.servicemaster.functions.AutoCompletion;
import com.servicemaster.functions.KeyCodeFunctions;
import com.servicemaster.guiFunctions.LableFunctions;
import com.servicemaster.models.Address;
import com.servicemaster.models.BusinessAddress;
import com.servicemaster.models.BusinessPartner;
import com.servicemaster.models.BusinessTelephone;
import com.servicemaster.models.Item;
import com.servicemaster.models.Service;
import com.servicemaster.models.ServiceBay;
import com.servicemaster.models.ServiceHasItem;
import com.servicemaster.models.Vehicle;
import com.servicemaster.timers.FocusTimer;
import com.servicemaster.utils.HibernateUtil;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.Timer;
import java.util.TreeMap;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Hibernate;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author RuwanM
 */
public class ServiceFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ServiceFrame
     *
     * @param service
     */
    public ServiceFrame(Service service) {
        initComponents();
        this.service = service;

        AutoCompletion.enable(cmbVehicle, txtLastServicesMilage);
        AutoCompletion.enable(cmbServiceBay, cmbItems);
        AutoCompletion.enable(cmbItems, txtQuantity);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discountGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        detailPanel = new javax.swing.JPanel();
        vehicleDetailPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLastServicesMilage = new javax.swing.JTextField();
        cmbVehicle = new javax.swing.JComboBox<>();
        btnNewVehicle = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        customerDetailPanel = new javax.swing.JPanel();
        lblAddress3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblAddress2 = new javax.swing.JLabel();
        ServiceDetailPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtGrandSubTotal = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGrandDiscount = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbServiceBay = new javax.swing.JComboBox<>();
        itemPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbItems = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JFormattedTextField();
        rbtPercentage = new javax.swing.JRadioButton();
        rbtNumber = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        detailPanel.setLayout(new java.awt.GridLayout(1, 0));

        vehicleDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Vehicle Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setText("Vehicle No :");

        jLabel2.setText("Last service milage :");

        txtLastServicesMilage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastServicesMilageKeyPressed(evt);
            }
        });

        cmbVehicle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVehicleItemStateChanged(evt);
            }
        });
        cmbVehicle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbVehicleFocusGained(evt);
            }
        });

        btnNewVehicle.setText("New");
        btnNewVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewVehicleActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehicleDetailPanelLayout = new javax.swing.GroupLayout(vehicleDetailPanel);
        vehicleDetailPanel.setLayout(vehicleDetailPanelLayout);
        vehicleDetailPanelLayout.setHorizontalGroup(
            vehicleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vehicleDetailPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbVehicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(vehicleDetailPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastServicesMilage, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        vehicleDetailPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        vehicleDetailPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNewVehicle, btnRefresh});

        vehicleDetailPanelLayout.setVerticalGroup(
            vehicleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewVehicle)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastServicesMilage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        vehicleDetailPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNewVehicle, cmbVehicle, jLabel1, jLabel2, txtLastServicesMilage});

        detailPanel.add(vehicleDetailPanel);

        customerDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        lblAddress3.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress3.setOpaque(true);

        jLabel3.setText("Customer Name :");

        jLabel4.setText("Address :");

        lblCustomerName.setBackground(new java.awt.Color(255, 255, 255));
        lblCustomerName.setOpaque(true);

        lblAddress1.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress1.setOpaque(true);

        lblAddress2.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress2.setOpaque(true);

        javax.swing.GroupLayout customerDetailPanelLayout = new javax.swing.GroupLayout(customerDetailPanel);
        customerDetailPanel.setLayout(customerDetailPanelLayout);
        customerDetailPanelLayout.setHorizontalGroup(
            customerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerDetailPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerDetailPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress2)
                            .addComponent(lblAddress1)
                            .addComponent(lblAddress3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerDetailPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4});

        customerDetailPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAddress1, lblAddress2, lblAddress3, lblCustomerName});

        customerDetailPanelLayout.setVerticalGroup(
            customerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(lblAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        detailPanel.add(customerDetailPanel);

        ServiceDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Service Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel5.setText("Sub Total :");

        txtGrandSubTotal.setEditable(false);
        txtGrandSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtGrandSubTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtGrandSubTotal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtGrandSubTotal.setText("0.00");

        jLabel6.setText("Discount :");

        txtGrandDiscount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtGrandDiscount.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtGrandDiscount.setText("0.00");

        jLabel7.setText("Grand Total :");

        txtGrandTotal.setEditable(false);
        txtGrandTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtGrandTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtGrandTotal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtGrandTotal.setText("0.00");

        jLabel11.setText("Service Bay :");

        javax.swing.GroupLayout ServiceDetailPanelLayout = new javax.swing.GroupLayout(ServiceDetailPanel);
        ServiceDetailPanel.setLayout(ServiceDetailPanelLayout);
        ServiceDetailPanelLayout.setHorizontalGroup(
            ServiceDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbServiceBay, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrandSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrandDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ServiceDetailPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7});

        ServiceDetailPanelLayout.setVerticalGroup(
            ServiceDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceDetailPanelLayout.createSequentialGroup()
                .addGroup(ServiceDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ServiceDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtGrandSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtGrandDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServiceDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cmbServiceBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        ServiceDetailPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7, txtGrandDiscount, txtGrandSubTotal, txtGrandTotal});

        itemPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel8.setText("Item Name :");

        cmbItems.setEditable(true);

        jLabel9.setText("Quantity :");

        txtQuantity.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtQuantity.setText("0.0");
        txtQuantity.setToolTipText("");
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantityFocusGained(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
        });

        jLabel10.setText("Discount :");

        txtDiscount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        txtDiscount.setText("0.0");

        discountGroup.add(rbtPercentage);
        rbtPercentage.setSelected(true);
        rbtPercentage.setText("%");
        rbtPercentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtPercentageKeyPressed(evt);
            }
        });

        discountGroup.add(rbtNumber);
        rbtNumber.setText("#");
        rbtNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtNumberKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbItems, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbtPercentage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel8, jLabel9});

        itemPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiscount, txtQuantity});

        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtPercentage)
                    .addComponent(rbtNumber))
                .addContainerGap())
        );

        itemPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbItems, jLabel10, jLabel8, jLabel9, txtDiscount, txtQuantity});

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Unit Price", "Sub Total", "Discount", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItems);
        if (tblItems.getColumnModel().getColumnCount() > 0) {
            tblItems.getColumnModel().getColumn(0).setResizable(false);
            tblItems.getColumnModel().getColumn(1).setResizable(false);
            tblItems.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblItems.getColumnModel().getColumn(2).setResizable(false);
            tblItems.getColumnModel().getColumn(3).setResizable(false);
            tblItems.getColumnModel().getColumn(4).setResizable(false);
            tblItems.getColumnModel().getColumn(5).setResizable(false);
            tblItems.getColumnModel().getColumn(6).setResizable(false);
        }

        lblClose.setBackground(new java.awt.Color(150, 255, 150));
        lblClose.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("Close");
        lblClose.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        lblUpdate.setBackground(new java.awt.Color(150, 255, 150));
        lblUpdate.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setText("Update");
        lblUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblUpdate.setOpaque(true);
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUpdateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblClose, lblUpdate});

        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblClose, lblUpdate});

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ServiceDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServiceDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ServiceDetailPanel, itemPanel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        ConfirmationDialog.showMessageBox("Are you sure?", "Sure");
        if (ConfirmationDialog.option == ConfirmationDialog.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked
        if (service != null) {

        } else {
            KeyCodeFunctions codeFunctions = new KeyCodeFunctions();
            String serviceCode = codeFunctions.getKey("SVR", "Service");
            Date date = new Date();

            service = new Service();
            service.setServiceCode(serviceCode);
            service.setMilage(Float.parseFloat(txtLastServicesMilage.getText().trim()));
            service.setCreatedDate(date);
            service.setCreatedTime(date);
            service.setCreatedUser(MainFrame.user.getUserId());
            service.setServiceBay(serviceBayMap.get(((String) cmbServiceBay.getSelectedItem()).trim()));
            service.setVehicle(vehicleMap.get(((String) cmbVehicle.getSelectedItem()).trim()));

            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();

            session.saveOrUpdate(service);

            DefaultTableModel tableModel = (DefaultTableModel) tblItems.getModel();
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                String itemName = (String) tblItems.getValueAt(i, 1);
                float quantity = (float) tblItems.getValueAt(i, 2);
                float subTotal = (float) tblItems.getValueAt(i, 4);
                float discount = (float) tblItems.getValueAt(i, 5);
                float itemTotal = (float) tblItems.getValueAt(i, 6);

                ServiceHasItem serviceHasItem = new ServiceHasItem();
                serviceHasItem.setItem(itemMap.get(itemName));
                serviceHasItem.setService(service);
                serviceHasItem.setQuantity(quantity);
                serviceHasItem.setSubTotal(subTotal);
                serviceHasItem.setDiscount(discount);
                serviceHasItem.setTotal(itemTotal);
                serviceHasItem.setCreatedDate(date);
                serviceHasItem.setCreatedTime(date);
                serviceHasItem.setCreatedUser(MainFrame.user.getUserId());
                serviceHasItem.setRemark(itemName);

                session.saveOrUpdate(serviceHasItem);
            }

            session.getTransaction().commit();
            session.close();
        }

        InformationDialog.showMessageBox("Updated successfully", "Success");
        this.resetWindow();
    }//GEN-LAST:event_lblUpdateMouseClicked

    private void lblUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblUpdateMouseEntered

    private void lblUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblUpdateMouseExited

    private void rbtPercentageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtPercentageKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT || evt.getKeyCode() == KeyEvent.VK_KP_RIGHT) {
            rbtPercentage.setSelected(false);
            rbtNumber.setSelected(true);
            rbtNumber.requestFocus();
        }
    }//GEN-LAST:event_rbtPercentageKeyPressed

    private void rbtNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtNumberKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT || evt.getKeyCode() == KeyEvent.VK_KP_LEFT) {
            rbtNumber.setSelected(false);
            rbtPercentage.setSelected(true);
            rbtPercentage.requestFocus();
        }
    }//GEN-LAST:event_rbtNumberKeyPressed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();

        this.loadVehicles(session);
        this.loadServiceBays(session);
        this.loadItems(session);

        session.getTransaction().commit();
        session.close();

        if (service == null) {
            this.lblUpdate.setText("Save");
            cmbVehicle.requestFocus();
        } else {
            session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();

            cmbVehicle.setSelectedItem(service.getVehicle().getVehicleNumber());
            txtLastServicesMilage.setText("" + service.getMilage());

            lblCustomerName.setText(service.getVehicle().getBusinessPartner().getFirstName() + " " + service.getVehicle().getBusinessPartner().getLastName());
            Set businessAddresses = service.getVehicle().getBusinessPartner().getBusinessAddresses();
            for (Object object : businessAddresses) {
                if (object instanceof BusinessAddress) {
                    BusinessAddress businessAddress = (BusinessAddress) object;
                    Address address = businessAddress.getAddress();
                    lblAddress1.setText(address.getAdressLine1());
                    lblAddress2.setText(address.getAdressLine2());
                    lblAddress3.setText(address.getAdressLine3());
                }
            }

            cmbServiceBay.setSelectedItem(service.getServiceBay().getServiceBayName());

            DefaultTableModel tableModel = (DefaultTableModel) tblItems.getModel();
            tableModel.setRowCount(0);
            Set serviceItems = service.getServiceHasItems();

            float tempGrandSubTotal = 0.0f;
            float tempGrandDiscount = 0.0f;
            float tempGrandTotal = 0.0f;

            for (Object object : serviceItems) {
                if (object instanceof ServiceHasItem) {
                    ServiceHasItem serviceItem = (ServiceHasItem) object;
                    Item item = serviceItem.getItem();

                    String itemCode = item.getItemCode();
                    String itemName = item.getItemName();
                    float quantity = serviceItem.getQuantity();
                    float unitPrice = item.getSellingPrice();
                    float subTotal = serviceItem.getSubTotal();
                    float discount = serviceItem.getDiscount();
                    float total = serviceItem.getTotal();

                    tableModel.addRow(new Object[]{itemCode, itemName, quantity, unitPrice, subTotal, discount, total});

                    tempGrandSubTotal += subTotal;
                    tempGrandDiscount += discount;
                    tempGrandTotal += total;
                }
            }

            txtGrandSubTotal.setText("" + tempGrandSubTotal);
            txtGrandDiscount.setText("" + tempGrandDiscount);
            txtGrandTotal.setText("" + tempGrandTotal);

            this.lblUpdate.setText("Update");

            session.close();
            
            Timer timer = new Timer();
            timer.schedule(new FocusTimer(), 500);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnNewVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewVehicleActionPerformed
        MainFrame.openWindow(MainFrame.allModuleMap.get("Vehicles"));
    }//GEN-LAST:event_btnNewVehicleActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();

        this.loadVehicles(session);

        session.getTransaction().commit();
        session.close();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void cmbVehicleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVehicleItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String vehicleNo = (String) cmbVehicle.getSelectedItem();
            if (!vehicleNo.isEmpty()) {
                Vehicle vehicle = vehicleMap.get(vehicleNo);
                BusinessPartner businessPartner = vehicle.getBusinessPartner();
                lblCustomerName.setText(businessPartner.getFirstName() + " " + businessPartner.getLastName());

                Set addresses = businessPartner.getBusinessAddresses();
                if (!addresses.isEmpty()) {
                    for (Object object : addresses) {
                        if (object instanceof BusinessAddress) {
                            BusinessAddress businessAddress = (BusinessAddress) object;
                            Address address = businessAddress.getAddress();
                            this.lblAddress1.setText(address.getAdressLine1());
                            this.lblAddress2.setText(address.getAdressLine2());
                            this.lblAddress3.setText(address.getAdressLine3());
                        }
                    }
                }

                Session session = HibernateUtil.getSessionFactory().openSession();
                session.beginTransaction();

                Query query = session.createQuery("from Service s where s.vehicle.vehicleNumber = :vehicleNumber ");
                query.setParameter("vehicleNumber", vehicle.getVehicleNumber());

                List list = query.list();
                if (!list.isEmpty()) {
                    for (Object object : list) {
                        if (object instanceof Service) {
                            Service tempService = (Service) object;
                            txtLastServicesMilage.setText(tempService.getMilage().toString());
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_cmbVehicleItemStateChanged

    private void txtLastServicesMilageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastServicesMilageKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cmbServiceBay.requestFocus();
        }
    }//GEN-LAST:event_txtLastServicesMilageKeyPressed

    private void txtQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusGained
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                txtQuantity.selectAll();
            }
        });
    }//GEN-LAST:event_txtQuantityFocusGained

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel tableModel = (DefaultTableModel) tblItems.getModel();
            String itemName = (String) cmbItems.getSelectedItem();
            Item item = itemMap.get(itemName);

            String itemCode = item.getItemCode();
            float quantity = Float.parseFloat(txtQuantity.getText().trim());
            float unitPrice = item.getSellingPrice();
            float subTotal = quantity * unitPrice;
            float discount = Float.parseFloat(txtDiscount.getText().trim());
            float total = subTotal - discount;

            tableModel.addRow(new Object[]{itemCode, itemName, quantity, unitPrice, subTotal, discount, total});

            cmbItems.setSelectedIndex(0);
            cmbItems.requestFocus();
            txtQuantity.setText("0.0");
            txtDiscount.setText("0.0");
            rbtPercentage.setSelected(true);

            grandSubTotal += subTotal;
            grandDiscount += discount;
            grandTotal += total;

            txtGrandSubTotal.setText("" + grandSubTotal);
            txtGrandDiscount.setText("" + grandDiscount);
            txtGrandTotal.setText("" + grandTotal);
        }
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked

    }//GEN-LAST:event_tblItemsMouseClicked

    private void cmbVehicleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbVehicleFocusGained
        if (service != null) {
            cmbItems.requestFocus();
        }
    }//GEN-LAST:event_cmbVehicleFocusGained

    private void loadVehicles(Session session) {

        Query query = session.createQuery("from Vehicle v order by v.vehicleNumber");
        List list = query.list();
        if (!list.isEmpty()) {
            cmbVehicle.removeAllItems();
            cmbVehicle.addItem("");
            for (Object object : list) {
                if (object instanceof Vehicle) {
                    Vehicle vehicle = (Vehicle) object;
                    String vehicleNo = vehicle.getVehicleNumber();

                    BusinessPartner businessPartner = vehicle.getBusinessPartner();
                    Hibernate.initialize(businessPartner);

                    Set addresses = businessPartner.getBusinessAddresses();
                    for (Object tempAddresse : addresses) {
                        if (tempAddresse instanceof BusinessAddress) {
                            BusinessAddress businessAddress = (BusinessAddress) tempAddresse;
                            Hibernate.initialize(businessAddress.getAddress());
                        }
                    }

                    Set businessTelephone = businessPartner.getBusinessTelephones();
                    for (Object tempTelephone : businessTelephone) {
                        if (tempTelephone instanceof BusinessTelephone) {
                            BusinessTelephone telephone = (BusinessTelephone) tempTelephone;
                            Hibernate.initialize(telephone.getTelephoneNumber());
                        }
                    }

                    cmbVehicle.addItem(vehicleNo);
                    vehicleMap.put(vehicleNo, vehicle);
                }
            }
        }
    }

    private void loadItems(Session session) {
        cmbItems.removeAllItems();
        cmbItems.addItem("");
        Query query = session.createQuery("from Item i order by i.itemName");
        List list = query.list();
        if (!list.isEmpty()) {
            for (Object object : list) {
                if (object instanceof Item) {
                    Item item = (Item) object;
                    String itemName = item.getItemName();
                    cmbItems.addItem(itemName);
                    itemMap.put(itemName, item);
                }
            }
        }
    }

    private void loadServiceBays(Session session) {
        cmbServiceBay.removeAllItems();
        cmbServiceBay.addItem("");
        Query query = session.createQuery("from ServiceBay sb order by sb.serviceBayCode");
        List list = query.list();
        if (!list.isEmpty()) {
            for (Object object : list) {
                if (object instanceof ServiceBay) {
                    ServiceBay serviceBay = (ServiceBay) object;
                    String serviceBayName = serviceBay.getServiceBayName();
                    cmbServiceBay.addItem(serviceBayName);
                    serviceBayMap.put(serviceBayName, serviceBay);
                }
            }
        }
    }

    private void resetWindow() {
        cmbVehicle.setSelectedIndex(0);
        txtLastServicesMilage.setText("");
        lblCustomerName.setText("");
        lblAddress1.setText("");
        lblAddress2.setText("");
        lblAddress3.setText("");

        cmbServiceBay.setSelectedIndex(0);
        txtGrandSubTotal.setText("0.00");
        txtGrandDiscount.setText("0.00");
        txtGrandTotal.setText("0.00");

        cmbItems.setSelectedIndex(0);
        txtQuantity.setText("0.00");
        txtDiscount.setText("0.00");
        rbtPercentage.setSelected(true);

        DefaultTableModel tableModel = (DefaultTableModel) tblItems.getModel();
        tableModel.setRowCount(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ServiceDetailPanel;
    private javax.swing.JButton btnNewVehicle;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel buttonPanel;
    public static javax.swing.JComboBox<String> cmbItems;
    private javax.swing.JComboBox<String> cmbServiceBay;
    private javax.swing.JComboBox<String> cmbVehicle;
    private javax.swing.JPanel customerDetailPanel;
    private javax.swing.JPanel detailPanel;
    private javax.swing.ButtonGroup discountGroup;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblAddress3;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton rbtNumber;
    private javax.swing.JRadioButton rbtPercentage;
    private javax.swing.JTable tblItems;
    private javax.swing.JFormattedTextField txtDiscount;
    private javax.swing.JFormattedTextField txtGrandDiscount;
    private javax.swing.JFormattedTextField txtGrandSubTotal;
    private javax.swing.JFormattedTextField txtGrandTotal;
    private javax.swing.JTextField txtLastServicesMilage;
    private javax.swing.JFormattedTextField txtQuantity;
    private javax.swing.JPanel vehicleDetailPanel;
    // End of variables declaration//GEN-END:variables
    private Service service;
    private final TreeMap<String, Vehicle> vehicleMap = new TreeMap<>();
    private final TreeMap<String, ServiceBay> serviceBayMap = new TreeMap<>();
    private final TreeMap<String, Item> itemMap = new TreeMap<>();

    private float grandSubTotal = 0.0f;
    private float grandTotal = 0.0f;
    private float grandDiscount = 0.0f;
}
