/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.servicemaster.internalFrames;

import com.servicemaster.data.SystemData;
import com.servicemaster.dialogs.InformationDialog;
import com.servicemaster.functions.JdbcConnection;
import com.servicemaster.guiFunctions.ButtonFunctions;
import java.sql.Connection;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ruwan Madawala
 */
public class StockReportFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form StockReportFrame
     */
    public StockReportFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        reportPanel = new javax.swing.JPanel();
        rbtStockBalanceReport = new javax.swing.JRadioButton();
        rbtInvoiceWiseProfitReport = new javax.swing.JRadioButton();
        optionPanel = new javax.swing.JPanel();
        dateChooserDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnVeiw = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Stock Reports");

        reportPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Report"));

        reportGroup.add(rbtStockBalanceReport);
        rbtStockBalanceReport.setSelected(true);
        rbtStockBalanceReport.setText("Stock Balance Report");
        rbtStockBalanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtStockBalanceReportActionPerformed(evt);
            }
        });

        reportGroup.add(rbtInvoiceWiseProfitReport);
        rbtInvoiceWiseProfitReport.setText("Invoice Wise Profit Report");
        rbtInvoiceWiseProfitReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtInvoiceWiseProfitReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtStockBalanceReport)
                    .addComponent(rbtInvoiceWiseProfitReport))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        reportPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbtInvoiceWiseProfitReport, rbtStockBalanceReport});

        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtStockBalanceReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtInvoiceWiseProfitReport)
                .addContainerGap())
        );

        reportPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbtInvoiceWiseProfitReport, rbtStockBalanceReport});

        optionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Potions"));

        dateChooserDate.setDate(new Date());
        dateChooserDate.setDateFormatString("yyyy-MM-dd");
        dateChooserDate.setEnabled(false);

        jLabel1.setText("Date :");

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(dateChooserDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        optionPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateChooserDate, jLabel1});

        btnClose.setBackground(new java.awt.Color(150, 255, 150));
        btnClose.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(true);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnVeiw.setBackground(new java.awt.Color(150, 255, 150));
        btnVeiw.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnVeiw.setText("View");
        btnVeiw.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnVeiw.setContentAreaFilled(false);
        btnVeiw.setOpaque(true);
        btnVeiw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVeiwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVeiwMouseExited(evt);
            }
        });
        btnVeiw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiwActionPerformed(evt);
            }
        });

        btnReset2.setBackground(new java.awt.Color(150, 255, 150));
        btnReset2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnReset2.setText("Reset");
        btnReset2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        btnReset2.setContentAreaFilled(false);
        btnReset2.setOpaque(true);
        btnReset2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReset2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReset2MouseExited(evt);
            }
        });
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReset2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVeiw, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVeiw, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtStockBalanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtStockBalanceReportActionPerformed
        this.enableComponents();
    }//GEN-LAST:event_rbtStockBalanceReportActionPerformed

    private void rbtInvoiceWiseProfitReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtInvoiceWiseProfitReportActionPerformed
        this.enableComponents();
    }//GEN-LAST:event_rbtInvoiceWiseProfitReportActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnVeiwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeiwMouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnVeiwMouseEntered

    private void btnVeiwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeiwMouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnVeiwMouseExited

    private void btnVeiwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiwActionPerformed
        Date date = new Date();
        String reportName;

        if (rbtStockBalanceReport.isSelected()) {
            date = new Date();
            reportName = "reports/StockBalanceReport.jasper";
        } else if (rbtInvoiceWiseProfitReport.isSelected()) {
            date = dateChooserDate.getDate();
            reportName = "reports/ProfitReport.jasper";
        } else {
            reportName = "";
        }

        if (!reportName.isEmpty()) {
            try {
                JdbcConnection jbConnection = new JdbcConnection();
                Connection connection = jbConnection.getConnection();

                Map map = new HashMap();
                map.put("date", date);

                JasperPrint jasperPrint = JasperFillManager.fillReport(reportName, map, connection);
                if (jasperPrint.getPages().size() > 0) {
                    JasperViewer.viewReport(jasperPrint, false);
                } else {
                    InformationDialog.showMessageBox("No records found", "Not Found", this);
                }
            } catch (JRException ex) {
                Logger.getLogger(SalesReportFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnVeiwActionPerformed

    private void btnReset2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReset2MouseEntered
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_btnReset2MouseEntered

    private void btnReset2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReset2MouseExited
        ButtonFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_btnReset2MouseExited

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        this.clearAll();
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void enableComponents() {
        if (rbtStockBalanceReport.isSelected()) {
            dateChooserDate.setEnabled(false);
        } else if (rbtInvoiceWiseProfitReport.isSelected()) {
            dateChooserDate.setEnabled(true);
        }
    }

    private void clearAll() {
        dateChooserDate.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnVeiw;
    private com.toedter.calendar.JDateChooser dateChooserDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JRadioButton rbtInvoiceWiseProfitReport;
    private javax.swing.JRadioButton rbtStockBalanceReport;
    private javax.swing.ButtonGroup reportGroup;
    private javax.swing.JPanel reportPanel;
    // End of variables declaration//GEN-END:variables
}
