package com.servicemaster.models;
// Generated Jul 26, 2017 11:33:46 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * InvoiceLine generated by hbm2java
 */
public class InvoiceLine  implements java.io.Serializable {


     private String invoiceLineCode;
     private Invoice invoice;
     private Float discount;
     private Float tax1;
     private Float tax2;
     private Float tax3;
     private Float tax4;
     private Float tax5;
     private Date createdDate;
     private Date createdTime;
     private Integer createdUser;
     private Date modifiedDate;
     private Date modifiedTime;
     private Integer modifiedUser;
     private String remark;

    public InvoiceLine() {
    }

	
    public InvoiceLine(String invoiceLineCode, Invoice invoice) {
        this.invoiceLineCode = invoiceLineCode;
        this.invoice = invoice;
    }
    public InvoiceLine(String invoiceLineCode, Invoice invoice, Float discount, Float tax1, Float tax2, Float tax3, Float tax4, Float tax5, Date createdDate, Date createdTime, Integer createdUser, Date modifiedDate, Date modifiedTime, Integer modifiedUser, String remark) {
       this.invoiceLineCode = invoiceLineCode;
       this.invoice = invoice;
       this.discount = discount;
       this.tax1 = tax1;
       this.tax2 = tax2;
       this.tax3 = tax3;
       this.tax4 = tax4;
       this.tax5 = tax5;
       this.createdDate = createdDate;
       this.createdTime = createdTime;
       this.createdUser = createdUser;
       this.modifiedDate = modifiedDate;
       this.modifiedTime = modifiedTime;
       this.modifiedUser = modifiedUser;
       this.remark = remark;
    }
   
    public String getInvoiceLineCode() {
        return this.invoiceLineCode;
    }
    
    public void setInvoiceLineCode(String invoiceLineCode) {
        this.invoiceLineCode = invoiceLineCode;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Float discount) {
        this.discount = discount;
    }
    public Float getTax1() {
        return this.tax1;
    }
    
    public void setTax1(Float tax1) {
        this.tax1 = tax1;
    }
    public Float getTax2() {
        return this.tax2;
    }
    
    public void setTax2(Float tax2) {
        this.tax2 = tax2;
    }
    public Float getTax3() {
        return this.tax3;
    }
    
    public void setTax3(Float tax3) {
        this.tax3 = tax3;
    }
    public Float getTax4() {
        return this.tax4;
    }
    
    public void setTax4(Float tax4) {
        this.tax4 = tax4;
    }
    public Float getTax5() {
        return this.tax5;
    }
    
    public void setTax5(Float tax5) {
        this.tax5 = tax5;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public Integer getCreatedUser() {
        return this.createdUser;
    }
    
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedTime() {
        return this.modifiedTime;
    }
    
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
    public Integer getModifiedUser() {
        return this.modifiedUser;
    }
    
    public void setModifiedUser(Integer modifiedUser) {
        this.modifiedUser = modifiedUser;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


