/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.servicemaster.views;

import com.servicemaster.data.SystemData;
import com.servicemaster.dialogs.ConfirmationDialog;
import com.servicemaster.guiFunctions.LableFunctions;
import com.servicemaster.internalFrames.BusinessPartnerFrame;
import com.servicemaster.models.Address;
import com.servicemaster.models.BusinessAddress;
import com.servicemaster.models.BusinessPartner;
import com.servicemaster.models.BusinessTelephone;
import com.servicemaster.models.TelephoneNumber;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RuwanM
 */
public class BusinessPatnerView extends javax.swing.JInternalFrame {

    private final List list;
    private final BusinessPartnerFrame businessPartnerFrame;

    /**
     * Creates new form CategoryView
     *
     * @param list
     * @param businessPatnerFrame
     */
    public BusinessPatnerView(List<BusinessPartner> list, BusinessPartnerFrame businessPatnerFrame) {
        initComponents();
        this.list = list;
        this.businessPartnerFrame = businessPatnerFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        businessPartnerTable = new javax.swing.JTable();
        lblSelect = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();

        setTitle("Category View");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        businessPartnerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus. Par. Code", "First Name", "Last Name", "Is Customer", "Is Supplier", "Is Employee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        businessPartnerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                businessPartnerTableMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(businessPartnerTable);

        lblSelect.setBackground(new java.awt.Color(150, 255, 150));
        lblSelect.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelect.setText("Select");
        lblSelect.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblSelect.setOpaque(true);
        lblSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSelectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSelectMouseExited(evt);
            }
        });

        lblClose.setBackground(new java.awt.Color(150, 255, 150));
        lblClose.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("Close");
        lblClose.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(50, 255, 50)));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(518, Short.MAX_VALUE)
                .addComponent(lblSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(scrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setBounds(0, 0, 700, 324);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        if (!list.isEmpty()) {
            DefaultTableModel tableModel = (DefaultTableModel) businessPartnerTable.getModel();
            tableModel.setRowCount(0);
            for (Object object : list) {
                if (object instanceof BusinessPartner) {
                    BusinessPartner businessPartner = (BusinessPartner) object;
                    tableModel.addRow(new Object[]{businessPartner.getBusinessPartnerCode(), businessPartner.getFirstName(),
                        businessPartner.getLastName(), businessPartner.isIsCustomer(), businessPartner.isIsSupplier(), businessPartner.isIsEmployee()});
                }
            }
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void businessPartnerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_businessPartnerTableMouseClicked
        int clickCount = evt.getClickCount();
        if (clickCount == 2) {
            this.selectBusinessPartner();
        }
    }//GEN-LAST:event_businessPartnerTableMouseClicked

    private void lblSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectMouseClicked
        this.selectBusinessPartner();
    }//GEN-LAST:event_lblSelectMouseClicked

    private void lblSelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblSelectMouseEntered

    private void lblSelectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblSelectMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        ConfirmationDialog.showMessageBox("Are you sure?", "Sure");
        if (ConfirmationDialog.option == ConfirmationDialog.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_ENTER_COLOR);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        LableFunctions.changeBackgroundColor(evt.getSource(), SystemData.MOUSE_EXIT_COLOR);
    }//GEN-LAST:event_lblCloseMouseExited

    private void selectBusinessPartner() {
        int selectedRow = businessPartnerTable.getSelectedRow();
        BusinessPartner businessPartner = (BusinessPartner) list.get(selectedRow);

        businessPartnerFrame.setBusinessPatnerCode(businessPartner.getBusinessPartnerCode());
        businessPartnerFrame.setFirstName(businessPartner.getFirstName());
        businessPartnerFrame.setLastName(businessPartner.getLastName());
        businessPartnerFrame.setNic(businessPartner.getNic());
        businessPartnerFrame.setBirthDay(businessPartner.getBirthDay());
        businessPartnerFrame.setIsCustomer(businessPartner.isIsCustomer());
        businessPartnerFrame.setIsSupplier(businessPartner.isIsSupplier());
        businessPartnerFrame.setIsEmployee(businessPartner.isIsEmployee());
        businessPartnerFrame.setIsActive((businessPartner.getIsActive() == 1));
        businessPartnerFrame.setRemark(businessPartner.getRemarks());

        Set addresses = businessPartner.getBusinessAddresses();
        if (!addresses.isEmpty()) {
            for (Object object : addresses) {
                if (object instanceof BusinessAddress) {
                    BusinessAddress businessAddress = (BusinessAddress) object;
                    Address address = businessAddress.getAddress();
                    businessPartnerFrame.setAddressLine1(address.getAddressCode() + "-" + address.getAdressLine1());
                    businessPartnerFrame.setAddressLine2(address.getAdressLine2());
                    businessPartnerFrame.setAddressLine3(address.getAdressLine3());
                }
            }
        }
        Set telephoneNumbers = businessPartner.getBusinessTelephones();
        if (!telephoneNumbers.isEmpty()) {
            for (Object object : telephoneNumbers) {
                if (object instanceof BusinessTelephone) {
                    BusinessTelephone businessTelephone = (BusinessTelephone) object;
                    TelephoneNumber telephoneNumber = businessTelephone.getTelephoneNumber();
                    businessPartnerFrame.setTelephoneNumber(telephoneNumber.getTelephoneNumberCode() + "-" + telephoneNumber.getTelephoneNumber());
                }
            }
        }
        businessPartnerFrame.setBusinessPatnerCodeEditable(false);
        businessPartnerFrame.setNicEditable(false);
        businessPartnerFrame.setLblSaveText("Update");
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable businessPartnerTable;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
